// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ikigai_api.Infrastructure.Persistence;

#nullable disable

namespace ikigai_api.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ikigai_api.Domain.Entities.DetailedComponentData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IkigaiSummaryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IkigaiSummaryId")
                        .IsUnique();

                    b.ToTable("DetailedComponentDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IkigaiResults");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DevelopmentPointsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResultId");

                    b.ToTable("IkigaiSummaries");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.LoveSessionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomHobbies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DreamAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedHobbies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopThreeHobbies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LoveSessionDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.PaidSessionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EverPaidAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MonetizableExperience")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedJobCards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaidSessionDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.PrologueData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SelectedReasons")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PrologueDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.SkillSessionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomHardSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomSoftSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedHardSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedSoftSkills")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SkillsMatchJob")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UseSkillsInNewRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SkillSessionDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.WorldSessionData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalledUponAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FutureValueAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MismatchChoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NoManualChoice")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SelectedGifts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorldSessionDatas");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.DetailedComponentData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.IkigaiSummary", "IkigaiSummary")
                        .WithOne("DetailedComponentData")
                        .HasForeignKey("ikigai_api.Domain.Entities.DetailedComponentData", "IkigaiSummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IkigaiSummary");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiResult", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("IkigaiResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiSummary", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.IkigaiResult", "Result")
                        .WithMany("IkigaiSummaries")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.LoveSessionData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("LoveSessionDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.PaidSessionData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("PaidSessionDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.PrologueData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("PrologueDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.SkillSessionData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("SkillSessionDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.WorldSessionData", b =>
                {
                    b.HasOne("ikigai_api.Domain.Entities.User", "User")
                        .WithMany("WorldSessionDatas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiResult", b =>
                {
                    b.Navigation("IkigaiSummaries");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.IkigaiSummary", b =>
                {
                    b.Navigation("DetailedComponentData");
                });

            modelBuilder.Entity("ikigai_api.Domain.Entities.User", b =>
                {
                    b.Navigation("IkigaiResults");

                    b.Navigation("LoveSessionDatas");

                    b.Navigation("PaidSessionDatas");

                    b.Navigation("PrologueDatas");

                    b.Navigation("SkillSessionDatas");

                    b.Navigation("WorldSessionDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
